FROM ekellener/awslambda
#VOLUME /home/app

# rebuild: docker build --build-arg git_repo=https://github.com/ekellener/alexa-icloudtools.git  -f reference-files/Dockerfile.alexa-icloudtools-appbuild -t ekellener/alexa-icloudtools-appbuild --no-cache .

# passing in rep to build
ARG git_repo

ENV HOME=/home/app
USER app
WORKDIR $HOME
# when using auth'd git; once public, can remove .ssh stmts
RUN echo "**** Pulling down recent repo"
RUN git clone $git_repo /home/app/lambda/alexa-icloudtools
WORKDIR $HOME/lambda/alexa-icloudtools
RUN npm install

